### PR TITLE
Create initial docker file

### PR DESCRIPTION
**Pull request by jwmoss**
[Pre-requisite PR](https://github.com/alex-phillips/plex-autocollections/pull/47)

A very (overly simplistic) dockerfile that supports running plex-autocollections in an automated fashion.

### CODE REVIEW

**Comment by alex-phillips** [comment]
Hey Jonathan! Good to see you agian, it's been a while!

And thanks for your interest in the project. The Dockerfile PR looks good, but would suggest that the entrypoint just refer to the old `main.py` to keep backwards compatibility with existing users / possible automations set up. The Dockerfile doesn't need a script called 'entrypoint' specifically. This should work fine:

```
CMD [ "python", "./main.py" ]
```

**Comment by jwmoss** [comment]
The problem with the existing main.py code is it's more "interactive" in that it prompts for the media library + credentials.

The code in #47 has support for passing 3 environment variables. That's the code that would be used here. Also, I'm not a python expert by any means, so #47 may not be what you're looking for.

**Comment by jwmoss** [comment]
Let me close #47 and submit a new PR with your latest changes to main.py. That way we can work off of the same code not a brand new codebase.

**Comment by jwmoss** [comment]
Opened #49 to add support for main.py ran inside docker.

**Comment by alex-phillips** [comment]
This looks good to me! Thanks!

**Pull request merged**
