### PR TITLE
Custom collections

### PR DESCRIPTION
**Pull request by tomhoover**
Implemented @michealespinola's custom collections idea (#25).

1. Any files added to the `collections.d` directory, with a filename ending in `.yml`, will be loaded/processed after `collections.yml`.
2. These 'custom collections' may be easily disabled by simply renaming them to something other than xxxxx.yml (e.g. for example, `my_custom_collection.yml.disabled`).
3. I've enabled two levels of debugging for testing (which I'll remove when @alex-phillips is agreeable to the change):
a. `DEBUG=1 python main.py` will display the filename of each custom collection as it is loaded.
b. `DEBUG=2 python main.py` will, in addition to the filename(s) displayed above, will also dump the actual data dictionary to the screen so that one may monitor the changes after each file is loaded/processed.
c. Or, one may run the script normally via `python main.py`.
4. For demonstration purposes, I've moved several of my recent PRs for `collections.yml` to custom collections: Addams Family, Atlas Shrugged, and Underworld. NOTE: The 'Addams Family' filename ends in `.disabled` to demonstrate that feature.

@alex-phillips, I see several advantages provided by this change:
1. Users will be able to track the 'master' branch of `plex-autocollections`, while still having the ability to add their own custom collections to their local machine.
2. You will have the ability to more liberally accept PRs that may not be of interest to all users (e.g. my recent [HUGE PR](#26) to add Hallmark Movies collection(s), which is probably too specialized, and large, to add to the master `collections.yml` file anway). You'll be able to accept PRs, such as this, provided they are saved to `collections.d` with a filename ending in `.disabled`. Users interested in the custom collection will simply rename the file.
3. Spitting up `collections.yml` into custom collections simply looks 'neater' and will be easier to maintain in the future. 😄 

I'm also interested in your thoughts how to further revise the README file to better explain the concept.

### CODE REVIEW

**Comment by tomhoover** [comment]
@alex-phillips, I kinda like the look of the DEBUG=1 messages:

* display the filename of each custom collection as it is loaded in "green"
* movie titles displayed in "red"
* collection names displayed in "blue"

Once you're OK with the PR, before merging it, I propose that I only remove the DEBUG=2 code and make the above DEBUG=1 messages "permanent".

**Comment by alex-phillips** [comment]
@tomhoover this looks great! Thanks for all the work. It doesn't hurt to have those debug options available in there and could prove useful in the future. I'm fine with keeping them both in unless you have a reason not to?

This really opens the door for more possibilities. I think next I'd like to implement a flag to specify a specific filename to process. This would be useful for updating a single collection without having to iterate over every collection to update one and having to rename (disable) collections just to update something like 'christmas.yml'.

Unless you want to make any more tweaks, I'd good to merge this!

**Comment by tomhoover** [comment]
Before you merge, let me move the custom collections into their own PR (i.e. separate the "code" changes from the custom collection changes--seems to be a little neater).

Also, do you want me to leave both DEBUG modes in? Or (as I suggested in my last comment above), convert DEBUG=1 (i.e. the green/red/blue colors) to be the default output? (I kinda like the colors. 😄 )

**Comment by alex-phillips** [comment]
All sounds good!

**Comment by tomhoover** [comment]
@alex-phillips, ready to merge.

**Pull request merged**
